language: objective-c
osx_image: xcode9.2

rvm:
- 2.2

before_install:  
- mkdir build
- chmod a+rwx build

- chmod a+x ./travis/env_test.sh
- chmod a+x ./travis/install.sh
- chmod a+x ./travis/build.sh

- brew install android-sdk
- export ANDROID_HOME=/usr/local/opt/android-sdk
- echo y | android update sdk --no-ui --all --filter "android-25,build-tools-25.0.2platform-tools,extra-android-m2repository,extra-google-m2repository

#- ./travis/env_test.sh

install:
- ./travis/install.sh

script:
- ./travis/build.sh

deploy:
  provider: testfairy
  api-key: "2d29db8bf7b2d619e995d2725f50db96f9564f42"
  app-file: build/application.apk
  keystore-file: user.keystore
  storepass: 12345678
  alias: alias
  auto-update: true
  skip_cleanup: true