language: objective-c
osx_image: xcode8.3

android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.2.3

    # The SDK version used to compile your project
    - android-25

rvm:
- 2.2
before_install:
- chmod a+x ./travis/install.sh
- chmod a+x ./travis/build.sh
install:
- ./travis/install.sh
script:
- ./travis/build.sh

deploy:
  provider: testfairy
  api-key: "2d29db8bf7b2d619e995d2725f50db96f9564f42"
  app-file: ./Build/uilatebinding.apk
  keystore-file: user.keystore
  storepass: 12345678
  alias: alias
  auto-update: true