language: objective-c
osx_image: xcode8.3



rvm:
- 2.2

before_install:  
- mkdir build
- chmod a+rwx build

- chmod a+x ./travis/env_test.sh
- chmod a+x ./travis/install.sh
- chmod a+x ./travis/build.sh

#- ./travis/env_test.sh

install:
- curl -o android-sdk.zip http://dl.google.com/android/android-sdk_r24.4.1-macosx.zip
- unzip android-sdk.zip
- ./travis/install.sh

script:
- ./travis/build.sh

#before_deploy:
#- ls -l /build/app.apk
#- cp /build/app.apk .

deploy:
  provider: testfairy
  api-key: "2d29db8bf7b2d619e995d2725f50db96f9564f42"
  app-file: build/application.apk
  keystore-file: user.keystore
  storepass: 12345678
  alias: alias
  auto-update: true
  skip_cleanup: true